### PR TITLE
fix incorrect GetNumAchievements declaration in ISteamUserStats011.h

### PR DESCRIPTION
**Pull request by criptych**
Rebased and cherry-picked from #3.

### CODE REVIEW

**Comment by VoiDeD** [comment]
Thanks.

Although I suppose it should be mentioned that I'm not sure we we're maintaining this codebase anymore, considering that the Steamworks SDK is public now.

**Comment by josh33901** [comment]
Afaik, steamworks is for interacting with steam_api rather than steam client. 
Last time I checked, there were no isteamclient or iclient interfaces.

**Comment by CookiePLMonster** [comment]
Maintaining OSW still makes sense I guess - especially because of the client interfaces which sometimes can be extra useful, but even using public Steamworks interfaces via OSW makes sense if one doesn't want to use steam_api.dll with the project.

**Comment by VoiDeD** [comment]
>there were no isteamclient or iclient interfaces.
ISteamClient is there, but the usage is just abstracted away by Steamworks. With enough work you can get at fairly easily.

As for IClient, we expose it but have always had the stance that users should not be using those interfaces as they're not version safe. We also rarely update them (likely nowhere near as fast as Valve is changing them).

**Pull request merged**
